/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_majiajie_codectest_NativeMethod */

#ifndef _Included_me_majiajie_codectest_NativeMethod
#define _Included_me_majiajie_codectest_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_majiajie_codectest_NativeMethod
 * Method:    Base64Decode
 * Signature: (Ljava/lang/String;[CCI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_majiajie_codectest_NativeMethod_Base64Decode
  (JNIEnv *, jclass, jstring, jcharArray, jchar, jint);

/*
 * Class:     me_majiajie_codectest_NativeMethod
 * Method:    Base64Encode
 * Signature: (Ljava/lang/String;[CCI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_majiajie_codectest_NativeMethod_Base64Encode
  (JNIEnv *, jclass, jstring, jcharArray, jchar, jint);

#ifdef __cplusplus
}
#endif
#endif
